#pragma once
#include <pgmspace.h>

typedef struct
{
    char name[11];
    uint8_t algo;
} DX7PatchInfo;

// Library contains 1024 DX7 patches
const DX7PatchInfo dx7_patches[1024] PROGMEM = {
    {"BRASS   1 ", 22},
    {"BRASS   2 ", 22},
    {"BRASS   3 ", 18},
    {"STRINGS 1 ", 2},
    {"STRINGS 2 ", 2},
    {"STRINGS 3 ", 15},
    {"ORCHESTRA ", 2},
    {"PIANO   1 ", 19},
    {"PIANO   2 ", 18},
    {"PIANO   3 ", 3},
    {"E.PIANO 1 ", 5},
    {"GUITAR  1 ", 8},
    {"GUITAR  2 ", 16},
    {"SYN-LEAD 1", 18},
    {"BASS    1 ", 16},
    {"BASS    2 ", 17},
    {"E.ORGAN 1 ", 32},
    {"PIPES   1 ", 19},
    {"HARPSICH 1", 5},
    {"CLAV    1 ", 3},
    {"VIBE    1 ", 23},
    {"MARIMBA   ", 7},
    {"KOTO      ", 2},
    {"FLUTE   1 ", 16},
    {"ORCH-CHIME", 5},
    {"TUB BELLS ", 5},
    {"STEEL DRUM", 15},
    {"TIMPANI   ", 16},
    {"REFS WHISL", 18},
    {"VOICE   1 ", 7},
    {"TRAIN     ", 5},
    {"TAKE OFF  ", 10},
    {"PIANO   4 ", 18},
    {"PIANO   5 ", 3},
    {"E.PIANO 2 ", 12},
    {"E.PIANO 3 ", 5},
    {"E.PIANO 4 ", 5},
    {"PIANO 5THS", 5},
    {"CELESTE   ", 31},
    {"TOY PIANO ", 30},
    {"HARPSICH 2", 3},
    {"HARPSICH 3", 3},
    {"CLAV    2 ", 4},
    {"CLAV    3 ", 4},
    {"E.ORGAN 2 ", 29},
    {"E.ORGAN 3 ", 29},
    {"E.ORGAN 4 ", 5},
    {"E.ORGAN 5 ", 29},
    {"PIPES   2 ", 3},
    {"PIPES   3 ", 25},
    {"PIPES   4 ", 6},
    {"CALIOPE   ", 16},
    {"ACCORDION ", 3},
    {"SITAR     ", 8},
    {"GUITAR  3 ", 14},
    {"GUITAR  4 ", 14},
    {"GUITAR  5 ", 14},
    {"GUITAR  6 ", 3},
    {"LUTE      ", 14},
    {"BANJO     ", 8},
    {"HARP    1 ", 3},
    {"HARP    2 ", 3},
    {"BASS    3 ", 17},
    {"BASS    4 ", 17},
    {"PICCOLO   ", 5},
    {"FLUTE   2 ", 18},
    {"OBOE      ", 3},
    {"CLARINET  ", 17},
    {"SAX BC    ", 18},
    {"BASSOON   ", 2},
    {"STRINGS 4 ", 2},
    {"STRINGS 5 ", 2},
    {"STRINGS 6 ", 15},
    {"STRINGS 7 ", 2},
    {"STRINGS 8 ", 2},
    {"BRASS   4 ", 22},
    {"BRASS   5 ", 2},
    {"BRASS 6 BC", 22},
    {"BRASS   7 ", 8},
    {"BRASS   8 ", 22},
    {"RECORDER  ", 6},
    {"HARMONICA1", 1},
    {"HRMNCA2 BC", 1},
    {"VOICE   2 ", 7},
    {"VOICE   3 ", 5},
    {"GLOKENSPL ", 7},
    {"VIBE    2 ", 5},
    {"XYLOPHONE ", 7},
    {"CHIMES    ", 6},
    {"GONG    1 ", 16},
    {"GONG    2 ", 17},
    {"BELLS     ", 27},
    {"COW BELL  ", 6},
    {"BLOCK     ", 18},
    {"FLEXATONE ", 7},
    {"LOG DRUM  ", 14},
    {"SYN-LEAD 2", 22},
    {"SYN-LEAD 3", 22},
    {"SYN-LEAD 4", 22},
    {"SYN-LEAD 5", 1},
    {"SYN-CLAV 1", 16},
    {"SYN-CLAV 2", 7},
    {"SYN-CLAV 3", 2},
    {"SYN-PIANO ", 5},
    {"SYNBRASS 1", 22},
    {"SYNBRASS 2", 22},
    {"SYNORGAN 1", 22},
    {"SYNORGAN 2", 3},
    {"SYN-VOX   ", 25},
    {"SYN-ORCH  ", 25},
    {"SYN-BASS 1", 3},
    {"SYN-BASS 2", 9},
    {"HARP-FLUTE", 3},
    {"BELL-FLUTE", 5},
    {"E.P-BRS BC", 5},
    {"T.BL-EXPA ", 5},
    {"CHIME-STRG", 5},
    {"B.DRM-SNAR", 3},
    {"SHIMMER   ", 5},
    {"EVOLUTION ", 1},
    {"WATER GDN ", 32},
    {"WASP STING", 18},
    {"LASER GUN ", 31},
    {"DESCENT   ", 1},
    {"OCTAVE WAR", 7},
    {"GRAND PRIX", 17},
    {"ST.HELENS ", 17},
    {"EXPLOSION ", 16},
    {"FLUTE   1 ", 16},
    {"HARPSICH 1", 5},
    {"STRG ENS 1", 15},
    {"BRIGHT BOW", 15},
    {"BRASSHORNS", 18},
    {"BR TRUMPET", 18},
    {"MARIMBA   ", 7},
    {"E.PIANO 1 ", 5},
    {"PIANO   1 ", 4},
    {"PIPES   1 ", 19},
    {"E.ORGAN 1 ", 32},
    {"E.BASS  1 ", 16},
    {"CLAV    1 ", 18},
    {"HARMONICA1", 1},
    {"JAZZ GUIT1", 8},
    {"PRC SYNTH1", 8},
    {"SAX BC    ", 18},
    {"FRETLESS 1", 17},
    {"HARP    1 ", 14},
    {"TIMPANI   ", 16},
    {"HEAVYMETAL", 14},
    {"STEEL DRUM", 15},
    {"SYN-LEAD 1", 18},
    {"VOICES BC ", 1},
    {"CLAV ENS  ", 4},
    {"LASERSWEEP", 31},
    {"TUB ERUPT ", 5},
    {"GRAND PRIX", 17},
    {"REFS WHISL", 18},
    {"TRAIN     ", 5},
    {"BRASS S H ", 18},
    {"TAKE OFF  ", 10},
    {"PIANO   2 ", 4},
    {"E.GRAND 1 ", 17},
    {"E.GRAND 2 ", 11},
    {"HONKY TONK", 3},
    {"E.PIANO 2 ", 12},
    {"E.PIANO 3 ", 6},
    {"E.PIANO 4 ", 5},
    {"CELESTE   ", 7},
    {"FUNK CLAV ", 18},
    {"CLAV ENS 2", 4},
    {"PERC CLAV ", 4},
    {"HARPSICH 2", 5},
    {"E.ORGAN 2 ", 29},
    {"E.ORGAN 3 ", 29},
    {"60-S ORGAN", 29},
    {"PIPES   2 ", 25},
    {"PIPES   3 ", 6},
    {"CALIOPE   ", 16},
    {"ACCORDION ", 4},
    {"TOY PIANO ", 30},
    {"SITAR     ", 8},
    {"KOTO      ", 2},
    {"JAZZ GUIT2", 8},
    {"SPANISHGTR", 14},
    {"FOLK GUIT ", 14},
    {"LUTE      ", 14},
    {"BANJO     ", 8},
    {"CLAS.GUIT ", 15},
    {"HARP    2 ", 3},
    {"E.BASS  2 ", 17},
    {"FRETLESS 2", 17},
    {"PLUCK BASS", 17},
    {"PICCOLO   ", 5},
    {"FLUTE   2 ", 18},
    {"OBOE      ", 3},
    {"CLARINET  ", 17},
    {"BASSOON   ", 2},
    {"PAN FLUTE ", 3},
    {"LEAD BRASS", 18},
    {"HORNS     ", 18},
    {"SOLO TBONE", 8},
    {"BRASS BC  ", 22},
    {"BRASS 5THS", 2},
    {"SYNTHBRASS", 22},
    {"STRG QRT 1", 2},
    {"STRG ENS 2", 9},
    {"VIOLA SECN", 15},
    {"STRGS LOW ", 2},
    {"HIGH STRGS", 2},
    {"PIZZ STGS ", 2},
    {"STG CRSNDO", 2},
    {"STGS 5THS ", 15},
    {"BELLS     ", 27},
    {"TUB BELLS ", 5},
    {"RECORDERS ", 6},
    {"CHIMES    ", 6},
    {"VOICES    ", 5},
    {"XYLOPHONE ", 7},
    {"COWBELL   ", 6},
    {"WOOD BLOCK", 18},
    {"FLEXATONE ", 7},
    {"LOG DRUM  ", 14},
    {"GLOKENSPL ", 7},
    {"VIBE      ", 23},
    {"CLAV-E.PNO", 9},
    {"PERC BRASS", 22},
    {"PRC SYNTH2", 3},
    {"HARPSI-STG", 5},
    {"CHIME-STRG", 5},
    {"HARP-FLUTE", 3},
    {"BELL-FLUTE", 5},
    {"STRG-CHIME", 2},
    {"STRG-MARIM", 15},
    {"STRG-PIZZT", 15},
    {"ORCHESTRA ", 2},
    {"LEAD GUITR", 7},
    {"PIANO-BRS ", 4},
    {"BRS-CHIME ", 22},
    {"B.DRM-SNAR", 3},
    {"E.P-BRS BC", 5},
    {"ORG-BRS BC", 31},
    {"CLV-BRS BC", 9},
    {"WHISTLES  ", 25},
    {"FILTER SWP", 17},
    {"FUNKY RISE", 2},
    {"WILD BOAR ", 1},
    {"SHIMMER   ", 5},
    {"EVOLUTION ", 1},
    {"WATER GDN ", 32},
    {"WASP STING", 18},
    {"MULTI NOTE", 32},
    {"DESCENT   ", 1},
    {"OCTAVE WAR", 7},
    {"..GOTCHA..", 8},
    {"ST.HELENS ", 17},
    {"EXPLOSION ", 16},
    {"PIANO    1", 10},
    {"PIANO    2", 3},
    {"PIANO    3", 3},
    {"HONKEY.P.F", 3},
    {"PLEPIARD  ", 3},
    {"PIANO-CP  ", 11},
    {"E.PIANO  1", 6},
    {"E.PIANO  2", 5},
    {"E.PIANO  3", 5},
    {"E.PIANO  4", 5},
    {"CEMBALO  1", 6},
    {"CEMBALO  2", 5},
    {"E-CEMBALO ", 17},
    {"CLAVI.   1", 18},
    {"CLAVI.   2", 4},
    {"CLAVI.   3", 18},
    {"CLAVI.   4", 17},
    {"CELESTE  1", 32},
    {"CELESTE  2", 32},
    {"AC.GUITAR1", 8},
    {"AC.GUITAR2", 8},
    {"AC.GUITAR3", 8},
    {"AC.GUITAR4", 1},
    {"12S.GUITAR", 3},
    {"E.GUITAR 1", 17},
    {"E.GUITAR 2", 20},
    {"E.GUITAR 3", 17},
    {"E.GUITAR 4", 18},
    {"E.GUITAR 5", 14},
    {"E.BASS   1", 16},
    {"E.BASS   2", 16},
    {"E.BASS   3", 11},
    {"E.BASS   4", 8},
    {"E.BASS   5", 17},
    {"SYN.BASS 1", 24},
    {"SYN.BASS 2", 17},
    {"SYN.BASS 3", 17},
    {"SYN.BASS 4", 15},
    {"SYN.BASS 5", 18},
    {"SYN.BASS 6", 18},
    {"W.BASS   1", 17},
    {"W.BASS   2", 17},
    {"W.BASS   3", 18},
    {"W.BASS   4", 3},
    {"ZITAR     ", 4},
    {"ZIMBALONE ", 6},
    {"BAMBOO MAR", 7},
    {"KARIMBA   ", 5},
    {"MANDOLIN 1", 13},
    {"MANDOLIN 2", 13},
    {"SITAR     ", 8},
    {"BANJO    1", 16},
    {"BANJO    2", 16},
    {"CHALANGO  ", 4},
    {"SHIYAMISEN", 2},
    {"BIWA      ", 18},
    {"VIB.    1 ", 23},
    {"VIB.    2 ", 5},
    {"GLOCKEN  1", 23},
    {"GLOCKEN  2", 7},
    {"XYLOPHONE ", 8},
    {"MARIMBA   ", 7},
    {"HANDBELL 1", 5},
    {"HANDBELL 2", 5},
    {"PICCOLO  1", 12},
    {"PICCOLO  2", 5},
    {"FLUTE    1", 15},
    {"FLUTE    2", 15},
    {"FLUTE    3", 15},
    {"ALTO FLUTE", 14},
    {"BASS FLUTE", 2},
    {"OBOE     1", 3},
    {"OBOE     2", 3},
    {"ENG.HORN  ", 4},
    {"CLARINET 1", 17},
    {"CLARINET 2", 16},
    {"CLARINET 3", 5},
    {"BASS CLA. ", 17},
    {"BASSOON  1", 23},
    {"BASSOON  2", 29},
    {"BASSOON  3", 3},
    {"SAXOPHONE1", 18},
    {"SAXOPHONE2", 18},
    {"SAXOPHONE3", 18},
    {"SAXOPHONE4", 18},
    {"HORN     1", 10},
    {"HORN     2", 9},
    {"HORN     3", 7},
    {"HORN     4", 7},
    {"HORN     5", 7},
    {"TRUMPET  1", 18},
    {"TRUMPET  2", 18},
    {"TRUMPET  3", 18},
    {"TRUMPET  4", 18},
    {"TRUMPET  5", 18},
    {"TRUMPET  6", 18},
    {"TRUMPET  7", 18},
    {"P.TRUMPET ", 16},
    {"TPT.MUTE 1", 18},
    {"TPT.MUTE 2", 7},
    {"FLUGELHORN", 8},
    {"TROMBONE 1", 18},
    {"TROMBONE 2", 18},
    {"TROMBONE 3", 18},
    {"TRB.MUTE 1", 7},
    {"TRB.MUTE 2", 7},
    {"TUBA      ", 18},
    {"RECORDER  ", 6},
    {"T.RECORDER", 5},
    {"OCARINA   ", 14},
    {"QUENA     ", 2},
    {"BAMBOO FL.", 5},
    {"PANFLUTE1 ", 7},
    {"PANFLUTE2 ", 14},
    {"BAGPIPE   ", 3},
    {"HARMONICA1", 30},
    {"HARMONICA2", 14},
    {"ACCORDION1", 4},
    {"ACCORDION2", 4},
    {"BRASS EN.1", 22},
    {"BRASS EN.2", 9},
    {"BRASS EN.3", 2},
    {"BRASS EN.4", 2},
    {"BRASS EN.5", 8},
    {"BRASS EN.6", 7},
    {"BRASS EN.7", 22},
    {"WIND ENS.1", 18},
    {"WIND ENS.2", 18},
    {"VIOLIN   1", 2},
    {"VIOLIN   2", 2},
    {"VIOLIN   3", 2},
    {"VIOLIN   4", 18},
    {"CELLO    1", 4},
    {"CELLO    2", 7},
    {"CONTRABASS", 15},
    {"STRINGS  1", 15},
    {"STRINGS  2", 15},
    {"STRINGS  3", 2},
    {"STRINGS  4", 11},
    {"STRINGS  5", 5},
    {"STRINGS  6", 2},
    {"STRINGS  7", 2},
    {"STRINGS  8", 2},
    {"STRINGS  9", 15},
    {"STRINGS 10", 15},
    {"STRINGS 11", 15},
    {"STR.PIZZ.1", 5},
    {"STR.PIZZ.2", 5},
    {"STR.PIZZ.3", 5},
    {"STR.PIZZ.4", 5},
    {"M. VOICE 1", 5},
    {"M. VOICE 2", 29},
    {"M. VOICE 3", 29},
    {"M. VOICE 4", 5},
    {"M. VOICE 5", 5},
    {"M. VOICE 6", 5},
    {"F. VOICE 1", 29},
    {"F. VOICE 2", 5},
    {"F. VOICE 3", 13},
    {"F. VOICE 4", 12},
    {"M.CHORUS 1", 29},
    {"M.CHORUS 2", 5},
    {"M.CHORUS 3", 24},
    {"M.CHORUS 4", 12},
    {"F.CHORUS 1", 7},
    {"F.CHORUS 2", 32},
    {"F.CHORUS 3", 8},
    {"CHORUS   1", 17},
    {"CHORUS   2", 9},
    {"CHORUS   3", 13},
    {"CHORUS   4", 13},
    {"CHORUS   5", 5},
    {"CHORUS   6", 24},
    {"VOC.VOICE ", 5},
    {"WHISTLE  1", 6},
    {"WHISTLE  2", 6},
    {"E. ORGAN 1", 29},
    {"E. ORGAN 2", 22},
    {"E. ORGAN 3", 29},
    {"E. ORGAN 4", 12},
    {"E. ORGAN 5", 29},
    {"E. ORGAN 6", 29},
    {"E. ORGAN 7", 29},
    {"E. ORGAN 8", 23},
    {"E. ORGAN 9", 29},
    {"E. ORGAN10", 29},
    {"BARREL ORG", 3},
    {"PIPE ORG.1", 32},
    {"PIPE ORG.2", 29},
    {"PIPE ORG.3", 6},
    {"PIPE ORG.4", 29},
    {"PIPE ORG.5", 5},
    {"DRUMS     ", 5},
    {"SNARE DR.1", 11},
    {"SNARE DR.2", 13},
    {"TOM-TOM  1", 17},
    {"TOM-TOM  2", 6},
    {"BASS DR. 1", 6},
    {"BASS DR. 2", 6},
    {"SIZ. CYMB.", 3},
    {"HI-HAT    ", 5},
    {"E. DRUMS 1", 16},
    {"E. DRUMS 2", 18},
    {"E. DRUMS 3", 1},
    {"E. DRUMS 4", 1},
    {"E. DRUMS 5", 1},
    {"TIMBALES 1", 7},
    {"TIMBALES 2", 16},
    {"CONGAS   1", 15},
    {"CONGAS   2", 17},
    {"JPN.DRUM 1", 16},
    {"JPN.DRUM 2", 3},
    {"JPN.DRUM 3", 16},
    {"JPN.DRUM 4", 4},
    {"QUIEKER   ", 13},
    {"TIMPANI  1", 16},
    {"TIMPANI  2", 17},
    {"HAND CLAP1", 2},
    {"HAND CLAP2", 7},
    {"TAP SLAP  ", 4},
    {"W. BLOCK 1", 6},
    {"W. BLOCK 2", 8},
    {"CASTANET 1", 6},
    {"CASTANET 2", 6},
    {"CLAVES    ", 6},
    {"GUIRO     ", 16},
    {"MARACAS   ", 16},
    {"KABASA    ", 16},
    {"TAMBLN.  1", 18},
    {"TAMBLN.  2", 18},
    {"SAMBA WHIS", 18},
    {"TRIANGLE 1", 23},
    {"TRIANGLE 2", 23},
    {"BELL TREE ", 23},
    {"SMALL BELL", 18},
    {"AGOGO     ", 15},
    {"GONG      ", 17},
    {"COW BELL 1", 15},
    {"COW BELL 2", 13},
    {"COW BELL 3", 13},
    {"WIND BELL1", 5},
    {"WIND BELL2", 5},
    {"STEEL DRUM", 15},
    {"GLASSHARP1", 16},
    {"GLASSHARP2", 12},
    {"REV.CYMB 1", 5},
    {"REV.CYMB 2", 5},
    {"SYN.PERC.1", 18},
    {"SYN.PERC.2", 14},
    {"SYN.PERC.3", 4},
    {"SYN.PERC.4", 17},
    {"SYN.PERC.5", 17},
    {"SYN.PERC.6", 17},
    {"SYN.PERC.7", 18},
    {"SYN.PERC.8", 4},
    {"SYN.PERC.9", 16},
    {"HEAVY RAIN", 17},
    {"THUNDER   ", 16},
    {"STORM    1", 12},
    {"STORM    2", 12},
    {"WATERDROP ", 23},
    {"BUBBLES   ", 18},
    {"WAVE     1", 17},
    {"WAVE     2", 2},
    {"WAVE     3", 2},
    {"WAVE     4", 5},
    {"RUMB.EARTH", 17},
    {"EXPLOSION1", 17},
    {"EXPLOSION2", 17},
    {"MAC.GUN  1", 16},
    {"MAC.GUN  2", 3},
    {"MOBILE   1", 18},
    {"MOBILE   2", 3},
    {"KLAXON    ", 5},
    {"MOTERCYCLE", 18},
    {"AMBULANCE ", 3},
    {"PATROL CAR", 3},
    {"SIREN     ", 9},
    {"PLAIN    1", 2},
    {"PLAIN    2", 10},
    {"HELICOPTER", 5},
    {"LOCOMOTIVE", 18},
    {"SHIP......", 18},
    {"TEL CALL 1", 17},
    {"TEL CALL 2", 3},
    {"BELL......", 23},
    {"PI.PO.PA. ", 6},
    {"ALARM!    ", 11},
    {"DOG       ", 3},
    {"BABY CAT  ", 21},
    {"INSECTS  1", 16},
    {"INSECTS  2", 16},
    {"INSECTS  3", 5},
    {"BIRD     1", 6},
    {"BIRD     2", 3},
    {"BIRD     3", 18},
    {"BIRD     4", 4},
    {"HEART BEAT", 18},
    {"TYPEWRITER", 7},
    {"CLOSING   ", 5},
    {"FACTORY   ", 18},
    {"ROBOT     ", 17},
    {"TEMP.BELL1", 5},
    {"TEMP.BELL2", 27},
    {"CHURCHBELL", 5},
    {"BIG BEN   ", 6},
    {"IMAGE    1", 6},
    {"IMAGE    2", 16},
    {"IMAGE    3", 1},
    {"IMAGE    4", 17},
    {"IMAGE    5", 18},
    {"IMAGE    6", 18},
    {"IMAGE    7", 18},
    {"IMAGE    8", 18},
    {"IMAGE    9", 5},
    {"IMAGE   10", 18},
    {"IMAGE   11", 7},
    {"IMAGE   12", 10},
    {"IMAGE   13", 16},
    {"IMAGE   14", 18},
    {"SYN.STR. 1", 15},
    {"SYN.STR. 2", 2},
    {"SYN.STR. 3", 2},
    {"SYN.STR. 4", 22},
    {"SYN.STR. 5", 22},
    {"SYN.STR. 6", 9},
    {"SYN.STR. 7", 3},
    {"SYN.STR. 8", 2},
    {"SYN.STR. 9", 18},
    {"SYN.STR.10", 2},
    {"SYN.STR.11", 9},
    {"SYN.STR.12", 18},
    {"SYN.STR.13", 9},
    {"SYN.BRA. 1", 3},
    {"SYN.BRA. 2", 5},
    {"SYN.BRA. 3", 18},
    {"SYN.BRA. 4", 17},
    {"SYN.BRA. 5", 18},
    {"SYN.BRA. 6", 18},
    {"SYN.BRA. 7", 22},
    {"SYN.BRA. 8", 18},
    {"SYN.BRA. 9", 18},
    {"SYN.BRA.10", 18},
    {"SYN.BRA.11", 3},
    {"SYN.BRA.12", 2},
    {"SYN.BRA.13", 18},
    {"SYN.LEAD 1", 24},
    {"SYN.LEAD 2", 6},
    {"SYN.LEAD 3", 5},
    {"SYN.LEAD 4", 6},
    {"SYN.LEAD 5", 6},
    {"SYN.LEAD 6", 18},
    {"SYN.BASS 7", 3},
    {"SYN.BASS 8", 14},
    {"SYN.BASS 9", 16},
    {"SYN.BASS10", 16},
    {"SYN. VOX 1", 3},
    {"SYN. VOX 2", 29},
    {"SYN. VOX 3", 23},
    {"SYN. VOX 4", 12},
    {"SYN. VOX 5", 4},
    {"SYN. VOX 6", 17},
    {"SYN.ORG. 1", 5},
    {"SYN.ORG. 2", 24},
    {"SYN.ORG. 3", 18},
    {"SYN.ORG. 4", 18},
    {"SYN.ORG. 5", 28},
    {"SYN.ORG. 6", 17},
    {"SYN.MARIM.", 7},
    {"SYN.CLAVI.", 18},
    {"SYN.HARMO.", 3},
    {"SYN.ORCHE.", 17},
    {"SYN.CHIM.1", 14},
    {"SYN.CHIM.2", 5},
    {"SYN.S.DRUM", 18},
    {"SYN.RECOR.", 18},
    {"SYN.GUITAR", 16},
    {"SYN.FLUTE ", 4},
    {"SYN.XYLOPH", 8},
    {"SYN.SITAR ", 1},
    {"SYN.GLOC.1", 5},
    {"SYN.GLOC.2", 6},
    {"SYN.GLOC.3", 23},
    {"SYN.GLOC.4", 16},
    {"Chorus PNO", 11},
    {"Tight  PNO", 16},
    {"Rock   PNO", 16},
    {"School PNO", 11},
    {"Wire   PNO", 16},
    {"<Pop> Epno", 9},
    {"<Brr> Epno", 19},
    {"<Wap> Epno", 9},
    {"<Puf> Orgn", 12},
    {"<Tap> Orgn", 16},
    {"<Big> Orgn", 12},
    {"Magicorgan", 5},
    {"Bigpipes  ", 12},
    {"<FM>alog 1", 2},
    {"<FM>alog 2", 17},
    {"<FM>alog 3", 28},
    {"<Pluk>   1", 16},
    {"<Pluk>   2", 17},
    {"<Pluk>   3", 16},
    {"Hav-a-Clav", 18},
    {"Magiklav  ", 10},
    {"Tenor  vox", 13},
    {"Lady   vox", 26},
    {"Vocoda vox", 4},
    {"Wahhh  vox", 4},
    {"Elec Brass", 2},
    {"Elec Viola", 16},
    {"Violin    ", 2},
    {"Hall Orch ", 12},
    {"1 fifth up", 3},
    {"Magiglokkk", 20},
    {"Magivybe  ", 6},
    {"Fingapikka", 9},
    {"Leadapikka", 17},
    {"Steelypika", 17},
    {"Classipika", 17},
    {"Harpsipika", 9},
    {"Pan floot ", 5},
    {"Huffsynth ", 17},
    {"Trompe    ", 9},
    {"Englishorn", 3},
    {"Harmosynth", 3},
    {"<FM>alog 4", 20},
    {"Backtalk  ", 11},
    {"Newtrumpet", 18},
    {"Elec comb ", 4},
    {"Touchbend ", 11},
    {"Bell<Wahh>", 11},
    {"Bowed bell", 19},
    {"Ting voice", 17},
    {"Cymbal    ", 9},
    {"Rubbergong", 18},
    {"Long gong ", 25},
    {"Smooh bass", 17},
    {"Bowed bass", 16},
    {"Oww bass  ", 4},
    {"Bass bass ", 12},
    {"Flunk bass", 17},
    {"Chain saw ", 15},
    {"Tambourine", 18},
    {"Thunderon ", 16},
    {"<<Smash>> ", 15},
    {"Handrum   ", 4},
    {"Congadrum ", 1},
    {"PickGuitar", 8},
    {"SongFlute ", 12},
    {"NewCeleste", 5},
    {"PianoBells", 5},
    {"MellowHorn", 2},
    {"MilkyWays ", 5},
    {"Xylo-Brass", 29},
    {"Rosin-Bows", 15},
    {"WireStrung", 9},
    {"DblTrumpet", 9},
    {"FullTines ", 5},
    {"Harpsi-Box", 9},
    {"}HardBass{", 22},
    {"PianoForte", 12},
    {"Good-Vibes", 2},
    {"Analog-DX7", 15},
    {"SpitFlute ", 12},
    {"St.Elmo's ", 5},
    {"Carolines ", 3},
    {"HarpStrum ", 3},
    {"ClaviPluck", 16},
    {"MalletHorn", 18},
    {"RaspySax  ", 18},
    {"HollowHits", 2},
    {"Hard~Tines", 7},
    {"FunkyPluck", 18},
    {"Whap-Synth", 13},
    {"SoloTrumpt", 18},
    {"ReverbStrg", 2},
    {"TouchOrg-1", 6},
    {"TouchOrg-2", 25},
    {"FM-Growth ", 17},
    {"ClaviStuff", 18},
    {"EchoMallet", 5},
    {"SteelCans ", 1},
    {"TackyPiano", 12},
    {"PlukGuitar", 18},
    {"HighStrung", 2},
    {"ChimeTines", 7},
    {"SoftFrench", 3},
    {"CongaClave", 5},
    {"Clave-Drum", 4},
    {"WoodSimmon", 2},
    {"CastePiano", 6},
    {"PianoFlute", 3},
    {"NeWaveOrgn", 22},
    {"ChorusRing", 9},
    {"EmerSynth ", 17},
    {"SoftPiano ", 19},
    {"Tine~Brass", 5},
    {"Orgn~Brass", 29},
    {"BCTrumpet ", 18},
    {"Xylophonk ", 18},
    {"SassyBrass", 18},
    {"ComicSiren", 5},
    {"Bugs&Birds", 5},
    {"RainDrops ", 4},
    {"Speak-One ", 15},
    {"Speak-Two ", 12},
    {"Speak-Thre", 9},
    {"Speak-Four", 9},
    {"What?One? ", 15},
    {"FM~Teapot ", 5},
    {"TapeRewind", 6},
    {"DX-PIANO  ", 5},
    {"DX-CP     ", 11},
    {"METAL PNO.", 10},
    {"CEMBABELL ", 5},
    {"CEMBALINE ", 5},
    {"CLATRON   ", 3},
    {"GLAVINET  ", 18},
    {"ORGAN.B-52", 31},
    {"ORGAN B-29", 29},
    {"ORGATORON ", 29},
    {"SYNTH.BELL", 1},
    {"GLASSPHONE", 16},
    {"METAL-GLOC", 1},
    {"SYN.HARP  ", 32},
    {"GLOCK-BOX ", 24},
    {"SYNTH CLIC", 5},
    {"JUICE HARP", 18},
    {"BELLCHIME ", 5},
    {"THUMHAPICA", 16},
    {"XYLO-HARP ", 7},
    {"METARIMBA ", 6},
    {"DIST.GUIT ", 14},
    {"8VER-GUIT ", 3},
    {"CLAGUITAR ", 8},
    {"SAMP.CONGA", 17},
    {"MARIM-BASS", 7},
    {"PICKIN-W.B", 17},
    {"METALBASS ", 4},
    {"IRON BASS ", 8},
    {"CLIC-BASS ", 16},
    {"SYN.BASS A", 4},
    {"SYN.BASS B", 4},
    {"ANDESFLUTE", 2},
    {"HOLE-FLUTE", 14},
    {"WIND-FLUTE", 15},
    {"BAMBOO CLA", 5},
    {"WIND-BRASS", 18},
    {"HARD BRASS", 18},
    {"BUSSY BRAS", 17},
    {"BRASTATION", 18},
    {"SOFT BRASS", 18},
    {"TRP.-TRB. ", 22},
    {"SOFT HORN ", 15},
    {"SYN.HORN  ", 10},
    {"SYNTHPHONE", 19},
    {"SOLO TROMB", 18},
    {"DX-TROMBA ", 18},
    {"D.QUART-ST", 2},
    {"A-TOUCH-ST", 15},
    {"SOFT STRGS", 31},
    {"NORMAL STG", 15},
    {"ANALOG-STG", 2},
    {"ORCH-STRGS", 2},
    {"LOWERSTRGS", 15},
    {"SOFT CHOIR", 31},
    {"WHISP-CHOR", 7},
    {"SOLO SYNTH", 15},
    {"IRON TIMPA", 16},
    {"METAL TOM ", 17},
    {"NOISY GLAS", 5},
    {"SNARE DRUM", 11},
    {"GATE REVER", 5},
    {"UP UP AWAY", 5},
    {"ANGEL FALL", 14},
    {"{KC}Piano\\", 16},
    {"ElecGrand\\", 13},
    {"EP DlyStr\\", 5},
    {"VicRhodes\\", 13},
    {"KC Tynot \\", 9},
    {"KC Ovrkil\\", 5},
    {"EpSqurMel\\", 23},
    {"WurliChrs\\", 10},
    {"EP.Dstrt \\", 12},
    {"BsEPiano8\\", 10},
    {"EP.SawBel\\", 5},
    {"EpDstrt *\\", 27},
    {"KC EpHwrd\\", 3},
    {"WoodBalls\\", 1},
    {"XyloHrdWd\\", 9},
    {"TorimLong\\", 9},
    {"Grinder 4\\", 11},
    {"Koto\\\\\\\\\\1", 7},
    {"SoftGuitr\\", 7},
    {"NylonPck3\\", 13},
    {"NylonBel3\\", 8},
    {"Sitar KC \\", 15},
    {"Chroma   \\", 3},
    {"Clavi 1  \\", 4},
    {"SqrThang2\\", 27},
    {"KillrD's5\\", 2},
    {"KilerD's2\\", 12},
    {"Bello 3~ \\", 26},
    {"Belashun \\", 22},
    {"RodeBell \\", 5},
    {"ChinezBls\\", 5},
    {"ElecBass*\\", 17},
    {"SoftEgStr\\", 2},
    {"Anna Str \\", 9},
    {"Xylo Str1\\", 5},
    {"Digi Pad \\", 9},
    {"AcSweep 2\\", 18},
    {"PedSweep2\\", 9},
    {"StrBrsPed\\", 9},
    {"TytPhaz//\\", 4},
    {"ObieBrs5/\\", 4},
    {"Anna Fat \\", 2},
    {"SaintWho \\", 6},
    {"Anna Hit1\\", 2},
    {"Anna Hit2\\", 2},
    {"SmoothSqr\\", 2},
    {"Sacuru   \\", 3},
    {"SwishBell\\", 5},
    {"Anna Xylo\\", 6},
    {"AcSmack 2\\", 18},
    {"AnnaNasty\\", 6},
    {"SubHarmLd\\", 26},
    {"Bel Lead \\", 19},
    {"LeadEcho1\\", 5},
    {"HrmnicaLd\\", 2},
    {"PennyFlut\\", 16},
    {"KC FLute4\\", 18},
    {"Dbl Reed \\", 27},
    {"TenrReed1\\", 27},
    {"3WySplt 1\\", 5},
    {"EchoEcho1\\", 22},
    {"EchoEcho2\\", 32},
    {"TapeRewnd2", 6},
    {"(A) -{440}", 1},
    {"Soft Spot\\", 4},
    {"Nu Island\\", 17},
    {"NuIsland2\\", 3},
    {"MarimBahh\\", 9},
    {"SftRimPlk\\", 9},
    {"RodeRasp1\\", 6},
    {"E.Clique1\\", 5},
    {"E.Clique2\\", 5},
    {"E.Clique3\\", 5},
    {"E.Clique4\\", 22},
    {"BassXylo1\\", 17},
    {"AcustcSt1\\", 11},
    {"AcustcSt2\\", 11},
    {"AcustcSt3\\", 11},
    {"NoBoKuto1\\", 11},
    {"MutronClv\\", 11},
    {"Clavinet2\\", 18},
    {"ClavSwep1\\", 4},
    {"ClavSwep2\\", 12},
    {"Screamer1\\", 16},
    {"LdSubHrm2\\", 26},
    {"BsE.Tack5\\", 18},
    {"BsE.Tack7\\", 18},
    {"NuMdlXprs\\", 10},
    {"DigiXylo1\\", 24},
    {"Jamaica 2\\", 18},
    {"NewCelest\\", 5},
    {"Glocker 1\\", 3},
    {"MuzacBox \\", 22},
    {"RodeBell2\\", 5},
    {"XprmntlBel", 16},
    {"Long Gong\\", 10},
    {"NogoKoto1\\", 9},
    {"DigiTar 1\\", 8},
    {"SoftElPno\\", 5},
    {"Fuhppps!2\\", 3},
    {"DblReed 2\\", 27},
    {"Flutos  5\\", 12},
    {"OB Geni 2\\", 6},
    {"DX Additv\\", 17},
    {"ChrchMows\\", 30},
    {"Chellezt1\\", 19},
    {"AgiFunki1\\", 1},
    {"AgiStop 1\\", 2},
    {"StrEnsmbl\\", 15},
    {"StrPd7%%%\\", 9},
    {"StrSweep \\", 29},
    {"SmrNParee\\", 26},
    {"Digi Pad \\", 29},
    {"Pad 16 Ft\\", 29},
    {"Brs 16Ft3\\", 29},
    {"Brs 16Ft4\\", 29},
    {"Trompet 1\\", 13},
    {"Ensemble2\\", 9},
    {"Trombone2\\", 18},
    {"FM Nazel1\\", 14},
    {"PdlSweep1\\", 9},
    {"PdlSweep2\\", 9},
    {"BetMeHrDr2", 18},
    {"BetMeHrDr3", 18},
    {"DesrtSean\\", 4},
    {"Vrbration2", 16},
    {"DropVolum\\", 17},
    {"LaserFall\\", 5},
    {"STARTXXX  ", 18},
    {"O-F-SEQ 1 ", 3},
    {"O-F-SEQ 2 ", 3},
    {"P.EGVOICE1", 7},
    {"P.EGVOICE2", 15},
    {"P.EGBRASS1", 2},
    {"P.EGBRASS2", 2},
    {"CHINA S&H1", 3},
    {"CHINA S&H2", 3},
    {"BRASZANCE1", 7},
    {"BRASZANCE2", 22},
    {"MILTONE   ", 5},
    {"REFLECTION", 18},
    {"FANTASY   ", 4},
    {"PACHICHORD", 18},
    {"NO.40     ", 2},
    {"EP-UNIT   ", 5},
    {"BRASS-UNIT", 15},
    {"GRACE STRG", 15},
    {"GRACEVOICE", 23},
    {"SANCTUS   ", 23},
    {"DIGI WOW  ", 16},
    {"DIGI LOG  ", 4},
    {"BALI GONG ", 22},
    {"KUTABEACH ", 5},
    {"MECHA KOTO", 3},
    {"MICHELLE  ", 15},
    {"ANTONIO   ", 2},
    {"LONG HAIR ", 28},
    {"SUS4 STRG.", 5},
    {"SPACE-TRIP", 23},
    {"SPACECHIME", 28},
    {"OPENING   ", 18},
    {"HITPAD 1  ", 17},
    {"HITPAD 2  ", 11},
    {"CLICK BASS", 4},
    {"SLAP BASS ", 18},
    {"MUTE BASS ", 18},
    {"PICKED GT.", 18},
    {"MUTELUTE  ", 19},
    {"THE DUCK  ", 3},
    {"BOULOUGNE ", 32},
    {"VIBE-COIN ", 3},
    {"AIR-XYL.  ", 18},
    {"PEKINGREED", 14},
    {"CROSSING  ", 6},
    {"DUTWAH    ", 2},
    {"REGGAE    ", 10},
    {"WOOD GONG1", 14},
    {"WOOD GONG2", 14},
    {"WOOD GONG3", 14},
    {"HEXAGON 1 ", 18},
    {"HEXAGON 2 ", 18},
    {"HEXAGON 3 ", 18},
    {"HEXA-B-DR.", 18},
    {"HEXA-GLASS", 28},
    {"GLOW BRASS", 9},
    {"OLDIES    ", 4},
    {"MUSIC BOX ", 5},
    {"EG BIAS   ", 4},
    {"NERVYHORNS", 1},
    {"HAMMER    ", 16},
    {"TEQUILA   ", 7},
    {"STARTREK  ", 1},
};
